### ISSUE TITLE
arm64 support

### ISSUE THREAD

**Issue by andreagdipaolo** [AsmSafone/MusicPlayer#11]
Will this project available for arm64?
When installing on an ARM sbc it gives a warning.

` ---> [Warning] The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested`

Thanks

**Comment by AsmSafone** [comment]
Did u get this on docker build method?

**Comment by andreagdipaolo** [comment]
Yes, local deployment on an ARM SBC (RK3399) with the exact commans present in the readme

**Comment by AsmSafone** [comment]
Try this way:
```
$ git clone https://github.com/AsmSafone/MusicPlayer
$ cd MusicPlayer
$ sudo apt install git curl python3-pip ffmpeg -y
$ pip3 install -U pip
$ curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash -
$ sudo apt install -y nodejs
$ sudo apt install build-essential
$ sudo npm install pm2@latest -g
$ pip3 install -U -r requirements.txt
# <create .env variables appropriately>
$ python3 main.py
```

**Comment by andreagdipaolo** [comment]
It works. Thanks!

Is it safe to update PyTgCalls to the last version or is it better to keep everything as you provide?

**Comment by AsmSafone** [comment]
> It works. Thanks!
> 
> Is it safe to update PyTgCalls to the last version or is it better to keep everything as you provide?

Pleasure!
Yah, u can! but always suggested to keep as it. coz its tested!

**Comment by AsmSafone** [comment]
Closing as [solved](https://github.com/AsmSafone/MusicPlayer/issues/11#issuecomment-1007476605).
