### ISSUE TITLE
Heroku Salesforce policy

### ISSUE THREAD

**Issue by alarskmoedig** [AsmSafone/MusicPlayer#12]
I Used That website. But still Salesforce. Then a bot in support group told me to rename that forked repo.. so i did it then it shows ( ```MusicPlayer/main.py``` not found) as vars ..

**Comment by AnonymousBoy1025** [comment]
Replace that music player with the renamed file name.

**Comment by alarskmoedig** [comment]
> Replace that music player with the renamed file name.

You mean mirror it ?

**Comment by AsmSafone** [comment]
fixed.
