### ISSUE TITLE
Deploy Problem

### ISSUE THREAD

**Issue by MarshmelloMusicerXD** [AsmSafone/MusicPlayer#25]
Hi, I'm ziad and I have an issue for deploying the project to heroku
![image](https://user-images.githubusercontent.com/68960255/179067184-66df5ad0-6de9-4d8c-9c8f-f5e514c729d8.png)
It cannot let me go to the deploy project (also my internet is cool it doesn't have any issue)
Please rely quick and Thanks for reading this.

**Comment by AsmSafone** [comment]
> Hi, I'm ziad and I have an issue for deploying the project to heroku ![image](https://user-images.githubusercontent.com/68960255/179067184-66df5ad0-6de9-4d8c-9c8f-f5e514c729d8.png) It cannot let me go to the deploy project (also my internet is cool it doesn't have any issue) Please rely quick and Thanks for reading this.

try now,,, fixed.
