### ISSUE TITLE
Another deploy problem (please don't remove this issue)

### ISSUE THREAD

**Issue by MarshmelloMusicerXD** [AsmSafone/MusicPlayer#26]
It's been 1 hour since Building the app and finished but not running and deploying to heroku

Here is an image for the problem
![image](https://user-images.githubusercontent.com/68960255/179274616-bf265a77-2d22-4910-b460-c08e7acc43ef.png)

**Comment by MarshmelloMusicerXD** [comment]
also what does sudo mean?

**Comment by AsmSafone** [comment]
> It's been 1 hour since Building the app and finished but not running and deploying to heroku
> 
> Here is an image for the problem ![image](https://user-images.githubusercontent.com/68960255/179274616-bf265a77-2d22-4910-b460-c08e7acc43ef.png)

its already deployed ig,, check apps!

**Comment by AsmSafone** [comment]
> also what does sudo mean?

[here u go](https://www.google.com/search?q=what+does+sudo+mean)..........>
