### ISSUE TITLE
Add a German json translation

### ISSUE THREAD

**Issue by denschiro** [AsmSafone/MusicPlayer#30]
Can i add a German translation to your Projekt?

**Comment by AsmSafone** [comment]
> Can i add a German translation to your Projekt?

Ofc, contributions are welcomed.

**Comment by manav0702** [comment]
Hi @AsmSafone  
Pls accept my PRs

**Comment by AsmSafone** [comment]
> Hi @AsmSafone Pls accept my PRs

please checkout contributing guideline and follow to be accepted.
