### ISSUE TITLE
Exception: MAX_RETRY_LIMIT_REACHED

### ISSUE THREAD

**Issue by Mister-Man7** [AsmSafone/MusicPlayer#42]
Traceback (most recent call last):
  File "/root/MusicPlayer/core/decorators.py", line 110, in decorator
    return await func(client, obj, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/MusicPlayer/main.py", line 103, in play_stream
    raise Exception(status)

**Comment by IM-SPYBOY** [comment]
> Traceback (most recent call last):
> 
>   File "/root/MusicPlayer/core/decorators.py", line 110, in decorator
> 
>     return await func(client, obj, *args)
> 
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/root/MusicPlayer/main.py", line 103, in play_stream
> 
>     raise Exception(status)

Same issue

**Comment by AsmSafone** [comment]
The issue caused by ytdl_p or maybe your requested url/song is inaccessible!

**Comment by ByEzel93** [comment]
I'm having the same problem too

```
Traceback (most recent call last):
  File "/www/wwwroot/cakir/bot/MusicPlayer/core/decorators.py", line 110, in decorator
    return await func(client, obj, *args)
  File "/www/wwwroot/cakir/bot/MusicPlayer/main.py", line 103, in play_stream
    raise Exception(status)
Exception: MAX_RETRY_LIMIT_REACHED
```

**Comment by AsmSafone** [comment]
> I'm having the same problem too
> 
> ```
> Traceback (most recent call last):
>   File "/www/wwwroot/cakir/bot/MusicPlayer/core/decorators.py", line 110, in decorator
>     return await func(client, obj, *args)
>   File "/www/wwwroot/cakir/bot/MusicPlayer/main.py", line 103, in play_stream
>     raise Exception(status)
> Exception: MAX_RETRY_LIMIT_REACHED
> ```

Retry redeploying, or check your server ip is not get blocked by youtube.
