### ISSUE TITLE
Error with received language code

### ISSUE THREAD

**Issue by wildmer** [AsmSafone/MusicPlayer#48]
I crashed with this error when running
```shell
FileNotFoundError: [Errno 2] No such file or directory: './lang/es_co:es.json'
``` 
![image](https://github.com/user-attachments/assets/62557ede-3dfd-4f62-b553-0ac1e549e2a6)

**Comment by AsmSafone** [comment]
There is no `es_co:es.json`, but there is `es.json` in the language directory. Please set the language code correctly.
