### ISSUE TITLE
Crash reported when play in different group

### ISSUE THREAD

**Issue by deulizealand** [AsmSafone/MusicPlayer#5]
Here the screenshot .
i have start music in 2 different group and in another group crashing no sound output
![image](https://user-images.githubusercontent.com/15981200/147375064-069e382d-3563-4736-98f1-2817070817f1.png)

**Comment by Achu2234** [comment]
> Here the screenshot . i have start music in 2 different group and in another group crashing no sound output ![image](https://user-images.githubusercontent.com/15981200/147375064-069e382d-3563-4736-98f1-2817070817f1.png)

you can see logs

**Comment by AsmSafone** [comment]
lol, cant u read last line? its not crashing its just a traceback when removing thumb file as u already removed it!

**Comment by AsmSafone** [comment]
> Here the screenshot . i have start music in 2 different group and in another group crashing no sound output ![image](https://user-images.githubusercontent.com/15981200/147375064-069e382d-3563-4736-98f1-2817070817f1.png)

perhaps this issue is [fixed](https://github.com/AsmSafone/MusicPlayer/commit/eed65819aedbbde7b760018f5b9fef83842435ce)
