### ISSUE TITLE
Error in queue

### ISSUE THREAD

**Issue by FilmBee** [AsmSafone/MusicPlayer#8]
When I add more than one in queue it crashes and says error. Also when I Import the exported queue the 2nd queue item don’t play and says error..

**Comment by AsmSafone** [comment]
Can u show the traceback?

**Comment by FilmBee** [comment]
Here is the Crash Log Form Saved Message

Traceback (most recent call last):
  File "/MusicPlayer/core/decorators.py", line 99, in decorator
    return await func(client, obj, *args)
  File "/MusicPlayer/main.py", line 193, in skip_track
    ok, status = await next_song.parse()
  File "/MusicPlayer/core/song.py", line 72, in parse
    video["thumbnail"], video["http_headers"]
KeyError: 'thumbnail'

**Comment by AsmSafone** [comment]
thats yt video issue that have no thumbnails. it can even handle unlimited queue. try others songs!
